FROM prom/prometheus:latest

USER root

# Copy the entrypoint script and set permissions
COPY prometheus-entrypoint.sh /usr/local/bin/prometheus-entrypoint.sh
RUN chmod 755 /usr/local/bin/prometheus-entrypoint.sh && \
    chown nobody:nobody /usr/local/bin/prometheus-entrypoint.sh

USER nobody

ENTRYPOINT ["/usr/local/bin/prometheus-entrypoint.sh"]
