# Monitoring Stack: Prometheus + Grafana + PostgreSQL Exporter + OpenTelemetry + Tempo
#
# Start with: docker compose -f compose.yaml -f compose.monitoring.yaml up -d
#
# All settings have sensible defaults. Override with environment variables if needed.

services:
  # PostgreSQL Exporter - exposes DB metrics for Prometheus
  postgres-exporter:
    image: prometheuscommunity/postgres-exporter:latest
    container_name: fhir-postgres-exporter
    restart: unless-stopped
    environment:
      DATA_SOURCE_NAME: "postgresql://${POSTGRES_USER:-fhir}:${POSTGRES_PASSWORD:-fhir}@db:5432/${POSTGRES_DB:-fhir}?sslmode=disable"
    ports:
      - "${POSTGRES_EXPORTER_PORT:-9187}:9187"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - fhir-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:9187/metrics"]
      interval: 10s
      timeout: 5s
      retries: 3

  # Prometheus - metrics collection
  prometheus:
    build:
      context: ./monitoring
      dockerfile: Dockerfile.prometheus
    image: fhir-prometheus:latest
    container_name: fhir-prometheus
    restart: unless-stopped
    environment:
      FHIR_SERVER_TARGET: ${FHIR_SERVER_TARGET:-fhir-server:8080}
    volumes:
      - ./monitoring/prometheus.yml.template:/etc/prometheus/prometheus.yml.template:ro
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=${PROMETHEUS_RETENTION:-30d}"
      - "--web.console.libraries=/etc/prometheus/console_libraries"
      - "--web.console.templates=/etc/prometheus/consoles"
      - "--web.enable-lifecycle"
    ports:
      - "${PROMETHEUS_PORT:-9090}:9090"
    depends_on:
      - postgres-exporter
    networks:
      - fhir-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:9090/-/healthy"]
      interval: 10s
      timeout: 5s
      retries: 3

  # OpenTelemetry Collector - receives, processes, and exports telemetry
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.93.0
    container_name: fhir-otel-collector
    restart: unless-stopped
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./monitoring/otel-collector-config.yaml:/etc/otel-collector-config.yaml:ro
    ports:
      - "${OTEL_GRPC_PORT:-4317}:4317"   # OTLP gRPC receiver
      - "${OTEL_HTTP_PORT:-4318}:4318"   # OTLP HTTP receiver
      - "${OTEL_METRICS_PORT:-8888}:8888" # Collector metrics
    networks:
      - fhir-network
    depends_on:
      - tempo
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:13133/"]
      interval: 10s
      timeout: 5s
      retries: 3

  # Grafana Tempo - distributed tracing backend
  tempo:
    image: grafana/tempo:2.3.1
    container_name: fhir-tempo
    restart: unless-stopped
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./monitoring/tempo-config.yaml:/etc/tempo.yaml:ro
      - tempo_data:/var/tempo
    ports:
      - "${TEMPO_PORT:-3200}:3200"       # Tempo HTTP API
      - "${TEMPO_OTLP_GRPC:-4319}:4319"  # OTLP gRPC (internal)
    networks:
      - fhir-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3200/ready"]
      interval: 10s
      timeout: 5s
      retries: 3

  # Grafana - visualization and dashboards
  grafana:
    image: grafana/grafana:latest
    container_name: fhir-grafana
    restart: unless-stopped
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_USER:-admin}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD:-admin}
      GF_INSTALL_PLUGINS: ${GRAFANA_PLUGINS:-grafana-clock-panel,grafana-simple-json-datasource,grafana-piechart-panel}
      GF_SERVER_ROOT_URL: ${GRAFANA_ROOT_URL:-http://localhost:3000}
      GF_USERS_ALLOW_SIGN_UP: "false"
      GF_DATABASE_LOCKING_ENABLED: "false"
      GF_PROVISIONING_DATASOURCES_ALLOW_DELETE: "true"
      GF_FEATURE_TOGGLES_ENABLE: "traceToMetrics tracesToLogsV2"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards:ro
    ports:
      - "${GRAFANA_PORT:-3000}:3000"
    depends_on:
      prometheus:
        condition: service_healthy
    networks:
      - fhir-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

volumes:
  prometheus_data:
    driver: local
  grafana_data:
    driver: local
  tempo_data:
    driver: local
